name: silab_admin
description: "A practicum management application of Information System."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0-190.0.dev <4.0.0"

dependencies:
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.1.1
  http: ^1.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_annotation: ^4.9.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
